namespace CarNumberRegionsTgBot.rus
{
	public class MilitaryCodesrus
	{
		public static Dictionary<int, string> MilitaryCodesrusAccordingToWiki = new Dictionary<int, string>
		{
			{ 9, "Military Construction Complex of the Ministry of Defense of the Russian Federation (VSK Ministry of Defense of Russia)" },
			{ 10, "Federal Security Service of the Russian Federation (FSB of Russia)" },
			{ 12, "Border Service of the Federal Security Service of the Russian Federation" },
			{ 14, "Railway Troops" },
			{ 15, "Federal National Guard Troops Service of the Russian Federation (Rosgvardia)" },
			{ 16, "Special Communications and Information Service of the Federal Protective Service of the Russian Federation (formerly FAPSI)" },
			{ 17, "Central Council of Defense Sports and Technical Organizations of the Russian Federation" },
			{ 18, "Ministry of the Russian Federation for Civil Defense, Emergencies, and Elimination of Consequences of Natural Disasters" },
			{ 20, "Federal Road Construction Administration under the Ministry of Defense of the Russian Federation" },
			{ 21, "Southern Military District" },
			{ 23, "Strategic Missile Forces" },
			{ 25, "Eastern Military District" },
			{ 26, "Reserve Equipment (long-term storage) of the Ground Forces of the Far Eastern Military District" },
			{ 27, "Air Defense Forces" },
			{ 29, "9th Central Directorate of the Ministry of Defense of the Russian Federation" },
			{ 32, "Trans-Baikal Military District (?)" },
			{ 34, "Air Force" },
			{ 35, "Ministry of Defense of the Russian Federation (Ministry of Defense of Russia)" },
			{ 39, "12th Main Directorate of the Ministry of Defense of the Russian Federation (nuclear support)" },
			{ 43, "Western Military District" },
			{ 45, "Navy" },
			{ 50, "Military Police" },
			{ 56, "Space Forces" },
			{ 65, "Central Military District" },
			{ 67, "Airborne Forces" },
			{ 76, "Central Military District" },
			{ 77, "Automobile Bases of the Ministry of Defense of Russia, General Staff of the Armed Forces of the Russian Federation, cargo and special vehicles of the Ministry of Defense of Russia" },
			{ 81, "Main Military Construction Directorate of the Ministry of Defense of the Russian Federation (GVSU Ministry of Defense of Russia)" },
			{ 82, "Main Directorate of Construction of the Ministry of Defense of the Russian Federation (GUS Ministry of Defense of Russia)" },
			{ 83, "Main Directorate of the Construction Industry of the Ministry of Defense of the Russian Federation (GUSP Ministry of Defense of Russia)" },
			{ 84, "Main Housing and Utilities Directorate of the Ministry of Defense of the Russian Federation (GKEU Ministry of Defense of Russia)" },
			{ 87, "Siberian Military District (SibVO)" },
			{ 88, "Central Military District" },
			{ 89, "Crimean Federal District" },
			{ 90, "Black Sea Fleet (Sevastopol)" },
			{ 91, "Baltic Fleet" },
			{ 92, "201st Gatchina Order of Zhukov Twice Red Banner Military Base, Tajikistan, 10th State Test Site 'Saryshagan', Priozersk, Kazakhstan" },
			{ 93, "Operational Group of Russian Forces in Transnistria" },
			{ 94, "Group of Russian Forces in the Transcaucasus" },
			{ 99, "Military Automobile Inspection of the Armed Forces of the Russian Federation" }
		};

		public static Dictionary<List<int>, List<string>> MilitaryCodesrusAccordingToLazLegend = new Dictionary<List<int>, List<string>>
		{
			{ new List<int> { 1, 2, 3, 4, 5, 6, 7, 8, 13 }, new List<string> { "Others", "—" } },
			{ new List<int> { 9 }, new List<string> { "VSK Ministry of Defense of Russia (since 2017)", "Military Construction Complex of the Ministry of Defense of the Russian Federation. Until 2016 - Federal Agency for Special Construction (Spetsstroy of Russia)." } },
			{ new List<int> { 10 }, new List<string> { "FSB of Russia (since 1995)", "Federal Security Service of the Russian Federation." } },
			{ new List<int> { 11, 15, 19 }, new List<string> { "VV Ministry of Internal Affairs of Russia (since 1992)", "Ministry of Internal Affairs of the Russian Federation (Internal Troops)." } },
			{ new List<int> { 12 }, new List<string> { "Border Service of the FSB of Russia (since 2003)", "Border Service of the FSB of Russia. From 1993 to 2003 - Federal Border Service of the Russian Federation (FPS of Russia)." } },
			{ new List<int> { 14 }, new List<string> { "Railway Troops of the Russian Armed Forces (since 2005)", "Railway Troops of the Armed Forces of the Russian Federation. From 1995 to 2004 - Federal Service for Railway Troops of Russia (FSZhV of Russia)." } },
			{ new List<int> { 16 }, new List<string> { "Special Communications Service of the FSO of Russia (since 2003)", "Special Communications and Information Service of the Federal Protective Service of the Russian Federation. From 1991 to 2003 - Federal Agency for Government Communications and Information under the President of the Russian Federation (FAPSI)." } },
			{ new List<int> { 17 }, new List<string> { "DOSAAF of Russia (since 2009)", "Volunteer Society for Cooperation with the Army, Aviation, and Navy of Russia. From 1991 to 2009 - Russian Defense Sports and Technical Organization (ROSTO)." } },
			{ new List<int> { 18 }, new List<string> { "Ministry of Emergency Situations of Russia (since 1990)", "Ministry of the Russian Federation for Civil Defense, Emergencies, and Elimination of Consequences of Natural Disasters." } },
			{ new List<int> { 20 }, new List<string> { "Road Troops of Russia (since 1990)", "Road Troops of Russia. From 1992 to 1997 - Federal Road Construction Administration under the Ministry of Defense of the Russian Federation (CDSU Ministry of Defense of Russia), (FDSU under the Ministry of Defense of Russia)." } },
			{ new List<int> { 21 }, new List<string> { "Southern Military District (since 2010)", "Southern Military District. From 1992 to 2010 - North Caucasian Military District (SKVO)." } },
			{ new List<int> { 23 }, new List<string> { "Strategic Missile Forces (since 1992)", "Strategic Missile Forces." } },
			{ new List<int> { 25 }, new List<string> { "Eastern Military District (since 2010)", "Eastern Military District. From 1992 to 2010 - Far Eastern Military District (KVO, DVO, DalVO)." } },
			{ new List<int> { 27 }, new List<string> { "Air Defense Forces (since 1992)", "Air Defense Forces of the Ground Forces of the Armed Forces of the Russian Federation." } },
			{ new List<int> { 29 }, new List<string> { "9th Central Directorate of the Ministry of Defense of the Russian Federation", "9th Central Directorate of the Ministry of Defense of the Russian Federation (commonly referred to as 'the ninth')." } },
			{ new List<int> { 32 }, new List<string> { "Central Military District and Eastern Military District (since 2010)", "Central Military District and Eastern Military District. From 1992 to 1998 - Trans-Baikal Military District (ZabVO). From 1998 to 2010 - Siberian Military District (SibVO)." } },
			{ new List<int> { 34 }, new List<string> { "Air Force (since 1992)", "Air Force." } },
			{ new List<int> { 39 }, new List<string> { "12th Main Directorate of the Ministry of Defense of the Russian Federation (since 1992)", "12th Main Directorate of the Ministry of Defense of the Russian Federation." } },
			{ new List<int> { 43 }, new List<string> { "Western Military District", "Western Military District. From 1992 to 2010 - Leningrad Military District (LenVO)." } },
			{ new List<int> { 45 }, new List<string> { "Navy (since 1992)", "Navy of the Russian Federation." } },
			{ new List<int> { 50 }, new List<string> { "Western Military District (since 2010)", "Western Military District. From 1992 to 2010 - Moscow Military District (MVO)." } },
			{ new List<int> { 56 }, new List<string> { "Space Forces (since 2015)", "Space Forces. From 1992 to 2001 - Military Space Forces (VKS). From 2001 to 2011 - Space Forces. From 2011 to 2015 - Aerospace Defense Forces." } },
			{ new List<int> { 65 }, new List<string> { "Central Military District (since 2010)", "Central Military District. From 1992 to 2001 - Volga Military District (PriVO). From 2001 to 2010 - Volga-Ural Military District (PUrVO)." } },
			{ new List<int> { 67 }, new List<string> { "Airborne Forces (since 1992)", "Airborne Forces of the Russian Federation." } },
			{ new List<int> { 76 }, new List<string> { "Central Military District (since 2010)", "Central Military District. From 1992 to 2001 - Ural Military District (UrVO). From 2001 to 2010 - Volga-Ural Military District." } },
			{ new List<int> { 77 }, new List<string> { "Automobile Bases of the Ministry of Defense of Russia and General Staff of Russia (1992-2009)", "Automobile bases of the General Staff of the Armed Forces of the Russian Federation, the Ministry of Defense of Russia, cargo and special vehicles of the Ministry of Defense of Russia, automobile bases of the GRU of the General Staff of the Armed Forces of Russia." } },
			{ new List<int> { 81 }, new List<string> { "Main Military Construction Directorate of the Ministry of Defense of the Russian Federation", "Main Military Construction Directorate of the Ministry of Defense of Russia." } },
			{ new List<int> { 82 }, new List<string> { "Main Directorate of Construction of the Ministry of Defense of the Russian Federation", "Main Directorate of Construction of the Ministry of Defense of Russia." } },
			{ new List<int> { 83 }, new List<string> { "Main Directorate of the Construction Industry of the Ministry of Defense of the Russian Federation", "Main Directorate of the Construction Industry of the Ministry of Defense of Russia." } },
			{ new List<int> { 87 }, new List<string> { "Central Military District (since 2010)", "Central Military District. From 1998 to 2010 - Siberian Military District (SibVO)." } },
			{ new List<int> { 90 }, new List<string> { "Black Sea Fleet of the Navy (since 1991)", "Black Sea Fleet of the Navy of Russia." } },
			{ new List<int> { 91 }, new List<string> { "11th Separate Air Defense Army (1992-1998)", "11th Separate Air Defense Army." } },
			{ new List<int> { 92 }, new List<string> { "201st Motorized Rifle Division (Tajikistan)", "201st Motorized Rifle Division." } },
			{ new List<int> { 93 }, new List<string> { "Operational Group of Russian Forces in the Transnistrian Region of the Republic of Moldova (since 1995)", "Operational Group of Russian Forces in the Transnistrian Region of Moldova." } },
			{ new List<int> { 94 }, new List<string> { "Group of Russian Forces in the Transcaucasus (1993-2007)", "Group of Russian Forces in the Transcaucasus." } },
			{ new List<int> { 99 }, new List<string> { "Military Automobile Inspection (since 1991)", "Military Automobile Inspection of the Armed Forces of the Russian Federation." } },
			{ new List<int> { 22, 24, 26, 28, 30, 31, 33, 35, 36, 37, 38, 40, 41, 42, 44, 46, 47, 48, 49, 51, 52, 53, 54, 55, 57, 58, 59, 60, 61, 62, 63, 64, 66, 68, 69, 70, 71, 72, 73, 74, 75, 78, 79, 80, 84, 85, 86, 88, 89, 95, 96, 97, 98 }, new List<string> { "Reserve", "—" } }
		};
	}
}
