namespace CarNumberRegionsTgBot.Ukraine
{
	public static class DiplomaticCodes
	{
		public static Dictionary<int, string> DiplomaticRepresentations = new Dictionary<int, string>
		{
			{ 1, "Not used, previously belonged to the Russian Federation" },
			{ 2, "United States of America" },
			{ 3, "People's Republic of China" },
			{ 4, "United Kingdom of Great Britain and Northern Ireland" },
			{ 5, "French Republic" },
			{ 6, "Federal Republic of Germany" },
			{ 7, "Hungary" },
			{ 8, "Republic of Lithuania" },
			{ 9, "Republic of Bulgaria" },
			{ 10, "Republic of Armenia" },
			{ 11, "Commonwealth of Australia" },
			{ 12, "State of Israel" },
			{ 13, "Republic of Belarus" },
			{ 14, "Republic of Poland" },
			{ 15, "Republic of Estonia" },
			{ 17, "Kingdom of Sweden" },
			{ 18, "United Mexican States" },
			{ 19, "Hellenic Republic (Greece)" },
			{ 20, "Republic of India" },
			{ 21, "Islamic Republic of Iran" },
			{ 22, "Mongolia" },
			{ 23, "Socialist Republic of Vietnam" },
			{ 24, "Republic of Austria" },
			{ 25, "Arab Republic of Egypt" },
			{ 26, "Argentine Republic" },
			{ 27, "Japan" },
			{ 28, "Canada" },
			{ 29, "Portuguese Republic" },
			{ 30, "Republic of Chile" },
			{ 31, "Italian Republic" },
			{ 32, "Kingdom of Spain" },
			{ 33, "Slovak Republic" },
			{ 34, "Romania" },
			{ 35, "Republic of Turkey" },
			{ 36, "Kingdom of Norway" },
			{ 37, "People's Democratic Republic of Algeria" },
			{ 38, "Swiss Confederation" },
			{ 39, "Republic of Niger" },
			{ 40, "State of Vatican City" },
			{ 41, "Republic of Azerbaijan" },
			{ 42, "Republic of Korea" },
			{ 43, "Federative Republic of Brazil" },
			{ 44, "Kingdom of Denmark" },
			{ 45, "Republic of Latvia" },
			{ 46, "Republic of Croatia" },
			{ 47, "Republic of Cyprus" },
			{ 48, "Czech Republic" },
			{ 49, "Republic of Finland" },
			{ 50, "Republic of Seychelles" },
			{ 51, "United Nations" },
			{ 52, "Central African Republic" },
			{ 53, "Republic of Slovenia" },
			{ 54, "Kingdom of Belgium" },
			{ 55, "Republic of Moldova" },
			{ 56, "Republic of Cuba" },
			{ 57, "Republic of the Philippines" },
			{ 58, "Republic of South Africa" },
			{ 59, "Islamic Republic of Pakistan" },
			{ 60, "Libyan Republic" },
			{ 61, "International Bank for Reconstruction and Development" },
			{ 62, "Lebanese Republic" },
			{ 64, "Republic of Singapore" },
			{ 65, "Republic of Ireland" },
			{ 66, "Kingdom of the Netherlands" },
			{ 67, "Republic of Kazakhstan" },
			{ 68, "Georgia" },
			{ 69, "Republic of Iraq" },
			{ 70, "Kyrgyz Republic" },
			{ 71, "Republic of Tajikistan" },
			{ 72, "Republic of Uzbekistan" },
			{ 73, "Turkmenistan" },
			{ 74, "Kingdom of Thailand" },
			{ 75, "Tunisian Republic" },
			{ 76, "Republic of Ghana" },
			{ 77, "Republic of Serbia" },
			{ 78, "Principality of Liechtenstein" },
			{ 79, "Republic of Indonesia" },
			{ 80, "Kingdom of Morocco" },
			{ 81, "Hashemite Kingdom of Jordan" },
			{ 82, "State of Kuwait" },
			{ 83, "Grand Duchy of Luxembourg" },
			{ 85, "Eastern Republic of Uruguay" },
			{ 86, "Republic of Peru" },
			{ 88, "Islamic Republic of Afghanistan" },
			{ 89, "Ukrainian Science and Technology Center (USTC)" },
			{ 91, "Republic of Albania" },
			{ 92, "North Macedonia" },
			{ 93, "NATO Liaison Office" },
			{ 94, "NATO Information Center" },
			{ 95, "International Monetary Fund" },
			{ 96, "New Zealand" },
			{ 97, "People's Republic of Bangladesh" },
			{ 98, "European Economic Community Commission" },
			{ 99, "European Bank for Reconstruction and Development" },
			{ 100, "Service Series" },
			{ 212, "Mission of the International Committee of the Red Cross in Ukraine" }
		};
	}
}
