namespace CarNumberRegionsTgBot.rus
{
    public class MilitaryCodesrus
    {
        public static Dictionary<int, string> MilitaryCodesrusAccordingToWiki = new Dictionary<int, string>
        {
            { 9, "military construction complex of the ministry of defense of the russian federation (vsk ministry of defense of russia)" },
            { 10, "federal security service of the russian federation (fsb of russia)" },
            { 12, "border service of the federal security service of the russian federation" },
            { 14, "railway troops" },
            { 15, "federal national guard troops service of the russian federation (rosgvardia)" },
            { 16, "special communications and information service of the federal protective service of the russian federation (formerly fapsi)" },
            { 17, "central council of defense sports and technical organizations of the russian federation" },
            { 18, "ministry of the russian federation for civil defense, emergencies, and elimination of consequences of natural disasters" },
            { 20, "federal road construction administration under the ministry of defense of the russian federation" },
            { 21, "southern military district" },
            { 23, "strategic missile forces" },
            { 25, "eastern military district" },
            { 26, "reserve equipment (long-term storage) of the ground forces of the far eastern military district" },
            { 27, "air defense forces" },
            { 29, "9th central directorate of the ministry of defense of the russian federation" },
            { 32, "trans-baikal military district (?)" },
            { 34, "air force" },
            { 35, "ministry of defense of the russian federation (ministry of defense of russia)" },
            { 39, "12th main directorate of the ministry of defense of the russian federation (nuclear support)" },
            { 43, "western military district" },
            { 45, "navy" },
            { 50, "military police" },
            { 56, "space forces" },
            { 65, "central military district" },
            { 67, "airborne forces" },
            { 76, "central military district" },
            { 77, "automobile bases of the ministry of defense of russia, general staff of the armed forces of the russian federation, cargo and special vehicles of the ministry of defense of russia" },
            { 81, "main military construction directorate of the ministry of defense of the russian federation (gvsu ministry of defense of russia)" },
            { 82, "main directorate of construction of the ministry of defense of the russian federation (gus ministry of defense of russia)" },
            { 83, "main directorate of the construction industry of the ministry of defense of the russian federation (gusp ministry of defense of russia)" },
            { 84, "main housing and utilities directorate of the ministry of defense of the russian federation (gkeu ministry of defense of russia)" },
            { 87, "siberian military district (sibvo)" },
            { 88, "central military district" },
            { 89, "crimean federal district" },
            { 90, "black sea fleet (sevastopol)" },
            { 91, "baltic fleet" },
            { 92, "201st gatchina order of zhukov twice red banner military base, tajikistan, 10th state test site 'saryshagan', priozersk, kazakhstan" },
            { 93, "operational group of russian forces in transnistria" },
            { 94, "group of russian forces in the transcaucasus" },
            { 99, "military automobile inspection of the armed forces of the russian federation" }
        };


        public static Dictionary<string, string> MilitaryCodesrusAccordingTolazlegend = new Dictionary<string, string>
        {
            { "1, 2, 3, 4, 5, 6, 7, 8, 13", "others —" },
            { "9", "vsk ministry of defense of russia (since 2017) - military construction complex of the ministry of defense of the russian federation. until 2016 - federal agency for special construction (spetsstroy of russia)." },
            { "10", "fsb of russia (since 1995) - federal security service of the russian federation." },
            { "11, 15, 19", "vv ministry of internal affairs of russia (since 1992) - ministry of internal affairs of the russian federation (internal troops)." },
            { "12", "border service of the fsb of russia (since 2003) - border service of the fsb of russia. from 1993 to 2003 - federal border service of the russian federation (fps of russia)." },
            { "14", "railway troops of the russian armed forces (since 2005) - railway troops of the armed forces of the russian federation. from 1995 to 2004 - federal service for railway troops of russia (fszhv of russia)." },
            { "16", "special communications service of the fso of russia (since 2003) - special communications and information service of the federal protective service of the russian federation. from 1991 to 2003 - federal agency for government communications and information under the president of the russian federation (fapsi)." },
            { "17", "dosaaf of russia (since 2009) - volunteer society for cooperation with the army, aviation, and navy of russia. from 1991 to 2009 - russian defense sports and technical organization (rosto)." },
            { "18", "ministry of emergency situations of russia (since 1990) - ministry of the russian federation for civil defense, emergencies, and elimination of consequences of natural disasters." },
            { "20", "road troops of russia (since 1990) - road troops of russia. from 1992 to 1997 - federal road construction administration under the ministry of defense of the russian federation (cdsu ministry of defense of russia), (fdsu under the ministry of defense of russia)." },
            { "21", "southern military district (since 2010) - southern military district. from 1992 to 2010 - north caucasian military district (skvo)." },
            { "23", "strategic missile forces (since 1992) - strategic missile forces." },
            { "25", "eastern military district (since 2010) - eastern military district. from 1992 to 2010 - far eastern military district (kvo, dvo, dalvo)." },
            { "27", "air defense forces (since 1992) - air defense forces of the ground forces of the armed forces of the russian federation." },
            { "29", "9th central directorate of the ministry of defense of the russian federation - 9th central directorate of the ministry of defense of the russian federation (commonly referred to as 'the ninth')." },
            { "32", "central military district and eastern military district (since 2010) - central military district and eastern military district. from 1992 to 1998 - trans-baikal military district (zabvo). from 1998 to 2010 - siberian military district (sibvo)." },
            { "34", "air force (since 1992) - air force." },
            { "39", "12th main directorate of the ministry of defense of the russian federation (since 1992) - 12th main directorate of the ministry of defense of the russian federation." },
            { "43", "western military district - western military district. from 1992 to 2010 - leningrad military district (lenvo)." },
            { "45", "navy (since 1992) - navy of the russian federation." },
            { "50", "western military district (since 2010) - western military district. from 1992 to 2010 - moscow military district (mvo)." },
            { "56", "space forces (since 2015) - space forces. from 1992 to 2001 - military space forces (vks). from 2001 to 2011 - space forces. from 2011 to 2015 - aerospace defense forces." },
            { "65", "central military district (since 2010) - central military district. from 1992 to 2001 - volga military district (privo). from 2001 to 2010 - volga-ural military district (purvo)." },
            { "67", "airborne forces (since 1992) - airborne forces of the russian federation." },
            { "76", "central military district (since 2010) - central military district. from 1992 to 2001 - ural military district (urvo). from 2001 to 2010 - volga-ural military district." },
            { "77", "automobile bases of the ministry of defense of russia and general staff of russia (1992-2009) - automobile bases of the general staff of the armed forces of the russian federation, the ministry of defense of russia, cargo and special vehicles of the ministry of defense of russia, automobile bases of the gru of the general staff of the armed forces of russia." },
            { "81", "main military construction directorate of the ministry of defense of the russian federation - main military construction directorate of the ministry of defense of russia." },
            { "82", "main directorate of construction of the ministry of defense of the russian federation - main directorate of construction of the ministry of defense of russia." },
            { "83", "main directorate of the construction industry of the ministry of defense of the russian federation - main directorate of the construction industry of the ministry of defense of russia." },
            { "87", "central military district (since 2010) - central military district. from 1998 to 2010 - siberian military district (sibvo)." },
            { "90", "black sea fleet of the navy (since 1991) - black sea fleet of the navy of russia." },
            { "91", "11th separate air defense army (1992-1998) - 11th separate air defense army." },
            { "92", "201st motorized rifle division (tajikistan) - 201st motorized rifle division." },
            { "93", "operational group of russian forces in the transnistrian region of the republic of moldova (since 1995) - operational group of russian forces in the transnistrian region of moldova." },
            { "94", "group of russian forces in the transcaucasus (1993-2007) - group of russian forces in the transcaucasus." },
            { "99", "military automobile inspection (since 1991) - military automobile inspection of the armed forces of the russian federation." },
            { "22, 24, 26, 28, 30, 31, 33, 35, 36, 37, 38, 40, 41, 42, 44, 46, 47, 48, 49, 51, 52, 53, 54, 55, 57, 58, 59, 60, 61, 62, 63, 64, 66, 68, 69, 70, 71, 72, 73, 74, 75, 78, 79, 80, 84, 85, 86, 88, 89, 95, 96, 97, 98", "reserve —" }
        };

    }
}
